# Generated by Django 3.2.4 on 2021-08-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.ImageField(default='gallery_ims/question_mark.png', upload_to='gallery_ims/'),
        ),
    ]
