# Generated by Django 3.2.4 on 2021-08-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_furniture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='furniture',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
    ]
